### ISSUE TITLE
Create new pyenv-pip-migrate release

### ISSUE THREAD

**Issue by dkav** [pyenv/pyenv-pip-migrate#6]
Can the team create a new release of pyenv-pip-migrate based on the latest head? The [current release](https://github.com/pyenv/pyenv-pip-migrate/releases/tag/v20130527) is built off the initial commit and doesn't include later commits. The release also includes a [bug](http://blog.maartenpaauw.com/2017/05/28/mktemp-mkstemp-failed-on-tmp-requirements-xxxx-txt-file-exists.html) that was fixed in a subsequent commit.

(A reposting from https://github.com/pyenv/pyenv/issues/1152)

**Comment by pfheatwole** [comment]
I see the chatter over at [homebrew-core](https://github.com/Homebrew/homebrew-core/pull/71525) looking for a tagged release. This "new" release should not suggest this plugin is actively developed, but I'm going to take the lack of recent issues as sufficient evidence that HEAD is stable.
